"use client";
import UITypography from "@/components/UITypography/UITypography";
import Head from "next/head";
import Image from "next/image";
import React, { useEffect } from "react";
import Young_Doug_About_Us from "../../../assets/Images/Young_Doug_About_Us.avif";

// export const metadata = {
//   title: "ABout",
//   description: "Generated by create next app",
// };
const About = () => {
  useEffect(() => {
    document.title = "My Data"; // Fallback for special cases
  }, []);
  return (
    <div className="p-container flex justify-center my-20">
      <div className="w-[90%] md:w-[70%] grid gap-6">
        {/* About Us */}
        <div className="flex flex-col gap-3">
          <UITypography variant="h3" text="About Us" />
          <UITypography variant="h5" text="Why Phoenix Sports?" />
          <UITypography text="Hi, I’m Douglas Goldfein, the founder of Phoenix Sports—where kids ages 3-10 discover the magic of movement, confidence, and teamwork! After years of teaching and coaching, I created Phoenix Sports to give kids more than just sports skills—I wanted them to experience the joy of play, build lifelong confidence, and learn critical life skills through teamwork and fun challenges." />
          <hr className="mt-6" />
        </div>

        {/* What Makes Us Different */}
        <div className="flex flex-col gap-3">
          <UITypography variant="h5" text="What Makes Us Different?" />
          <UITypography text="At Phoenix Sports, it’s not just about mastering the game; it’s about growing minds, strong bodies, and kind hearts. With small group sizes, every child gets the attention they deserve. Our sessions build on each other, breaking sports down into simple, achievable steps tailored to every age and skill level." />
          <hr className="mt-6" />
        </div>

        {/* Meet the Team */}
        <div className="flex flex-col gap-3">
          <UITypography variant="h5" text="Meet the Team" />
          <UITypography text="Our coaches are not only sports experts but also mentors who care deeply about your child’s growth. Every coach is CPR/First Aid certified and trained in safety protocols, but more importantly, they bring their passion for teaching and their love of the game to every session." />
          <hr className="mt-6" />
        </div>

        {/* My Journey */}
        <div className="flex flex-col gap-3">
          <UITypography variant="h5" text="My Journey" />
          <UITypography text="Born and raised in Chicago, I grew up loving soccer, basketball, and baseball—and cheering on the Cubs and Packers (yes, it’s a thing!). My journey took me to Taiwan, where I taught English for seven years before earning my Master’s in Education. After coaching for Skyhawks Sports Academy and training coaches, I knew it was time to create something special. That dream became Phoenix Sports in Carlsbad, CA—a place where kids can thrive, on and off the field." />
          <hr className="mt-6" />
        </div>

        {/* Our Philosophy */}
        <div className="flex flex-col gap-3">
          <UITypography variant="h5" text="Our Philosophy" />
          <UITypography text="We believe sports should be fun, inclusive, and empowering. That’s why we focus on building self-confidence, patience, and social skills through teamwork and positive interactions. Our non-competitive environment ensures kids feel safe to grow, learn, and reach new milestones at their own pace." />
          <UITypography text="At Phoenix Sports, it’s not just about sports—it’s about raising confident, kind, and active kids who love the game and love themselves. Let’s play! 🎉" />
          <hr className="mt-6" />
        </div>

        {/* Staff Members */}
        <div className="flex flex-col gap-3">
          <UITypography variant="h5" text="Staff Members" />
          <UITypography text="Douglas Goldfein" />
          <Image src={Young_Doug_About_Us} alt="Young_Doug_About_Us" height={120} />
        </div>
      </div>
    </div>
  );
};

export default About;
