export const SignupConstants = {
  SIGN_UP_LOADING: "SIGN_UP_LOADING",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_ERROR: "SIGN_UP_ERROR",
};
export const EmailVerifyConstants = {
  EMAIL_VERIFY_LOADING: "EMAIL_VERIFY_LOADING",
  EMAIL_VERIFY_SUCCESS: "EMAIL_VERIFY_SUCCESS",
  EMAIL_VERIFY_ERROR: "EMAIL_VERIFY_ERROR",
};

export const SignInConstants = {
  SIGN_IN_LOADING: "SIGN_IN_LOADING",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_ERROR: "SIGN_IN_ERROR",
};

export const EditCategoryDataConstants = {
  EDIT_CATEGORY_DATA_LOADING: "EDIT_CATEGORY_DATA_LOADING",
  EDIT_CATEGORY_DATA_SUCCESS: "EDIT_CATEGORY_DATA_SUCCESS",
  EDIT_CATEGORY_DATA_ERROR: "EDIT_CATEGORY_DATA_ERROR",
};

export const GetAllCategoriesConstants = {
  GET_ALL_CATEGORIES_LOADING: "GET_ALL_CATEGORIES_LOADING",
  GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
  GET_ALL_CATEGORIES_ERROR: "GET_ALL_CATEGORIES_ERROR",
};

export const EditSubCategoryDataConstants = {
  EDIT_SUB_CATEGORY_DATA_LOADING: "EDIT_SUB_CATEGORY_DATA_LOADING",
  EDIT_SUB_CATEGORY_DATA_SUCCESS: "EDIT_SUB_CATEGORY_DATA_SUCCESS",
  EDIT_SUB_CATEGORY_DATA_ERROR: "EDIT_SUB_CATEGORY_DATA_ERROR",
};

export const GetAllSubCategoriesConstants = {
  GET_ALL_SUB_CATEGORIES_LOADING: "GET_ALL_SUB_CATEGORIES_LOADING",
  GET_ALL_SUB_CATEGORIES_SUCCESS: "GET_ALL_SUB_CATEGORIES_SUCCESS",
  GET_ALL_SUB_CATEGORIES_ERROR: "GET_ALL_SUB_CATEGORIES_ERROR",
};

export const GetAllProductsConstants = {
  GET_ALL_PRODUCTS_LOADING: "GET_ALL_PRODUCTS_LOADING",
  GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
  GET_ALL_PRODUCTS_ERROR: "GET_ALL_PRODUCTS_ERROR",
};

export const EditProductsConstants = {
  EDIT_PRODUCTS_DATA_LOADING: "EDIT_PRODUCTS_DATA_LOADING",
  EDIT_PRODUCTS_DATA_SUCCESS: "EDIT_PRODUCTS_DATA_SUCCESS",
  EDIT_PRODUCTS_DATA_ERROR: "EDIT_PRODUCTS_DATA_ERROR",
};
export const ProductDataConstants = {
  PRODUCT_DATA_LOADING: "PRODUCT_DATA_LOADING",
  PRODUCT_DATA_SUCCESS: "PRODUCT_DATA_SUCCESS",
  PRODUCT_DATA_ERROR: "PRODUCT_DATA_ERROR",
};
export const GetAllChildrenConstants = {
  GET_ALL_CHILDREN_LOADING: "GET_ALL_CHILDREN_LOADING",
  GET_ALL_CHILDREN_SUCCESS: "GET_ALL_CHILDREN_SUCCESS",
  GET_ALL_CHILDREN_ERROR: "GET_ALL_CHILDREN_ERROR",
};
export const SelectProductCheckoutConstants = {
  SELECT_PRODUCT_CHECKOUT_LOADING: "SELECT_PRODUCT_CHECKOUT_LOADING",
  SELECT_PRODUCT_CHECKOUT_SUCCESS: "SELECT_PRODUCT_CHECKOUT_SUCCESS",
  SELECT_PRODUCT_CHECKOUT_ERROR: "SELECT_PRODUCT_CHECKOUT_ERROR",
};
export const EditChildrenDataConstants = {
  EDIT_CHILDREN_DATA_LOADING: "EDIT_CHILDREN_DATA_LOADING",
  EDIT_CHILDREN_DATA_SUCCESS: "EDIT_CHILDREN_DATA_SUCCESS",
  EDIT_CHILDREN_DATA_ERROR: "EDIT_CHILDREN_DATA_ERROR",
};